# Generated by Django 4.2.2 on 2023-06-20 15:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("RecommendSystem", "0003_rename_book_id_blacklist_book_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Favorites",
            new_name="Favorite",
        ),
    ]
