# Generated by Django 4.2.2 on 2023-06-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RecommendSystem", "0012_alter_comment_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="rating",
        ),
    ]
