# Generated by Django 4.2.7 on 2023-11-23 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("RecommendSystem", "0014_like_dislike"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Автора", "verbose_name_plural": "Авторы"},
        ),
        migrations.AlterModelOptions(
            name="blacklist",
            options={"verbose_name": "Запись", "verbose_name_plural": "Черный список"},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "Книгу", "verbose_name_plural": "Книги"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterModelOptions(
            name="dislike",
            options={"verbose_name": "Дизлайк", "verbose_name_plural": "Дизлайки"},
        ),
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Список любимых книг",
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "Жанр", "verbose_name_plural": "Жанры"},
        ),
        migrations.AlterModelOptions(
            name="like",
            options={"verbose_name": "Лайк", "verbose_name_plural": "Лайки"},
        ),
        migrations.AlterField(
            model_name="author",
            name="description",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="author",
            name="firstname",
            field=models.CharField(max_length=200, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="author",
            name="image",
            field=models.ImageField(
                default="images/authors/default.png",
                upload_to="images/authors/",
                verbose_name="Фотография",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="lastname",
            field=models.CharField(max_length=200, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="author",
            name="patronymic",
            field=models.CharField(max_length=200, verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="blacklist",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="RecommendSystem.book",
                verbose_name="Книга",
            ),
        ),
        migrations.AlterField(
            model_name="blacklist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="annotation",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="RecommendSystem.author",
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="RecommendSystem.genre",
                verbose_name="Жанр",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                default="images/book_faces/default.png",
                upload_to="images/book_faces/",
                verbose_name="Изображение обложки",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.IntegerField(default=0, verbose_name="Рейтинг"),
        ),
        migrations.AlterField(
            model_name="book",
            name="year",
            field=models.IntegerField(verbose_name="Год издания"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="RecommendSystem.book",
                verbose_name="Книга",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="Дата написания"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="dislike",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="RecommendSystem.book",
                verbose_name="Книга",
            ),
        ),
        migrations.AlterField(
            model_name="dislike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="RecommendSystem.book",
                verbose_name="Книга",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="genre_name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="like",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="RecommendSystem.book",
                verbose_name="Книга",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalGenre",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "genre_name",
                    models.CharField(max_length=200, verbose_name="Название"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Жанр",
                "verbose_name_plural": "historical Жанры",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBook",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "book_name",
                    models.CharField(max_length=200, verbose_name="Название"),
                ),
                (
                    "image",
                    models.TextField(
                        default="images/book_faces/default.png",
                        max_length=100,
                        verbose_name="Изображение обложки",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Год издания")),
                ("rating", models.IntegerField(default=0, verbose_name="Рейтинг")),
                ("annotation", models.TextField(null=True, verbose_name="Описание")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="RecommendSystem.author",
                        verbose_name="Автор",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="RecommendSystem.genre",
                        verbose_name="Жанр",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Книгу",
                "verbose_name_plural": "historical Книги",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAuthor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("firstname", models.CharField(max_length=200, verbose_name="Имя")),
                ("lastname", models.CharField(max_length=200, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(max_length=200, verbose_name="Отчество"),
                ),
                (
                    "image",
                    models.TextField(
                        default="images/authors/default.png",
                        max_length=100,
                        verbose_name="Фотография",
                    ),
                ),
                ("description", models.TextField(null=True, verbose_name="Описание")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Автора",
                "verbose_name_plural": "historical Авторы",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
