# Generated by Django 4.2.7 on 2023-11-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "RecommendSystem",
            "0015_alter_author_options_alter_blacklist_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_hide",
            field=models.BooleanField(default=False, verbose_name="Скрыт"),
        ),
    ]
